<?php
/* Module mdl_custom
 * Use any custom work for site
 * Author Zeeshan khan
 * Dated 27-02-14
 */

/*
 * Implement hook_node_view
 * Use add Export link on node detail page.
 */
function mdl_custom_node_view($node, $view_mode) {
  if ($node->type == 'profiles') {
	 if ($view_mode == 'full') {
        $node->content['export_content']['link']['Export'] = array(
           '#type' => 'link',
           '#prefix' => '',
           '#title' => t('Export'),
           '#href' => "node/$node->nid/data-export",
           '#suffix' => '',
           '#weight'=> -1
        );  
     }
    return $node;
   }
}

/*
 * Implement hook_menu
 * Use create urls for charts.
 */
function mdl_custom_menu() {
    $items['service-line'] = array(
        'title' => 'Service Line View',
        'page callback' => 'service_line_chart',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['sectors'] = array(
        'title' => 'Sectors View',
        'page callback' => 'sectors_chart',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function service_line_chart() {
  $output='';
  $service_line_name = taxonomy_vocabulary_machine_name_load('service_line');
  $service_line_vid = $service_line_name->vid;
  $service_line = taxonomy_get_tree($service_line_vid);
  
  $geography_name = taxonomy_vocabulary_machine_name_load('geography');
  $geography_vid = $geography_name->vid;
  $geography = taxonomy_get_tree($geography_vid);
  $n1 = array();
  $n2 = array(); 
 
  foreach($geography as $geo){
   $n1[] = $tids = array($geo->tid);
  }
  foreach($service_line as $sv){
   $n2[] = $tids = array($sv->tid);
  }
 
  $output .= '<table><tr class="th-row"><th>Row Labels</th>';
  foreach($geography as $geo){
   $output .= '<th>'.$geo->name.'</th>';
  }
  $output .= '</tr>';
  
  for($i =0; $i<count($service_line); $i++ ){
	  $output .= '<tr><td>'.$service_line[$i]->name.'</td>';
	  $nids1 = taxonomy_select_nodes($n2[$i]);
	 
	  for($j =0; $j<count($geography); $j++ ){
		  $nids2 = taxonomy_select_nodes($n1[$j]);
		  $a = check_common_nids($nids1,$nids2);
		  $output .= '<td>'.count($a);
		  $output .= '</td>'; 
	 }
	 $output .= '</tr>';
  }
   $output .= '</table>';
  return $output;
}
function check_common_nids($nid1, $nid2) {
	return $commonElements = array_intersect($nid1,$nid2);
}
function sectors_chart() {
  $output='';
  $sectors_name = taxonomy_vocabulary_machine_name_load('sectors');
  $sectors_vid = $sectors_name->vid;
  $sectors = taxonomy_get_tree($sectors_vid);
  $geography_name = taxonomy_vocabulary_machine_name_load('geography');
  $geography_vid = $geography_name->vid;
  $geography = taxonomy_get_tree($geography_vid);
   
  $n1 = array();
  $n2 = array(); 
 
  foreach($geography as $geo){
   $n1[] = $tids = array($geo->tid);
  }
  foreach($sectors as $sec){
   $n2[] = $tids = array($sec->tid);
  }
 
  $output .= '<table><tr class="th-row"><th>Row Labels</th>';
  foreach($geography as $geo){
   $output .= '<th>'.$geo->name.'</th>';
  }
  $output .= '</tr>';
  
  for($i =0; $i<count($sectors); $i++ ){
	  $output .= '<tr><td>'.$sectors[$i]->name.'</td>';
	  $nids1 = taxonomy_select_nodes($n2[$i]);
	 
	  for($j =0; $j<count($geography); $j++ ){
		  $nids2 = taxonomy_select_nodes($n1[$j]);
		  $a = check_common_nids($nids1,$nids2);
		  $output .= '<td>'.count($a);
		  $output .= '</td>'; 
	 }
	 $output .= '</tr>';
  }
   $output .= '</table>';
  
  return $output;
}

function all_chart() {
  $output='';
  $status_name = taxonomy_vocabulary_machine_name_load('status');
  $status_vid = $status_name->vid;
  $status = taxonomy_get_tree($status_vid);
 
  $geography_name = taxonomy_vocabulary_machine_name_load('geography');
  $geography_vid = $geography_name->vid;
  $geography = taxonomy_get_tree($geography_vid);
  
  $n1 = array();
  $n2 = array(); 
 
  foreach($geography as $geo){
   $n1[] = $tids = array($geo->tid);
  }
  foreach($status as $sta){
   $n2[] = $tids = array($sta->tid);
  }
 
  $output .= '<table><tr class="th-row"><th>Row Labels</th>';
  foreach($geography as $geo){
   $output .= '<th>'.$geo->name.'</th>';
  }
  $output .= '</tr>';
  
  for($i =0; $i<count($status); $i++ ){
	  $output .= '<tr><td>'.$status[$i]->name.'</td>';
	  $nids1 = taxonomy_select_nodes($n2[$i]);
	 
	  for($j =0; $j<count($geography); $j++ ){
		  $nids2 = taxonomy_select_nodes($n1[$j]);
		  $a = check_common_nids($nids1,$nids2);
		  $output .= '<td>'.count($a);
		  $output .= '</td>'; 
	 }
	 $output .= '</tr>';
  }
   $output .= '</table>';
  
  return $output;
}

function mdl_custom_block_info() {
   $blocks['current_status'] = array(
    'info' => t('Current Status'), 
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}
function mdl_custom_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'current_status':
      $block['subject'] = t('Current Status');
      $block['content'] = all_chart();
      break;

  }
  return $block;
}
