<?php
/* Module mdl_custom
 * Use any custom work for site
 * Author Zeeshan khan
 * Dated 27-02-14
 */

/*
 * Implement hook_node_view
 * Use add Export link on node detail page.
 */
function mdl_custom_node_view($node, $view_mode) {
  if ($node->type == 'profiles') {
	 if ($view_mode == 'full') {
        $node->content['export_content']['link']['Export'] = array(
           '#type' => 'link',
           '#prefix' => '',
           '#title' => t('Export'),
           '#href' => "node/$node->nid/data-export",
           '#suffix' => '',
           '#weight'=> -1
        );  
     }
    return $node;
   }
}

/*
 * Implement hook_menu
 * Use create urls for charts.
 */
function mdl_custom_menu() {
    $items['service-line'] = array(
        'title' => 'Service Line View',
        'page callback' => 'service_line_chart',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['sectors'] = array(
        'title' => 'Sectors View',
        'page callback' => 'sectors_chart',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

/*
 * Implement service_line_chart()
 * Use display Service Line Chart.
 */
 
function service_line_chart() {
  $output='';
  $service_line_name = taxonomy_vocabulary_machine_name_load('service_line');
  $service_line_vid = $service_line_name->vid;
  $service_line = taxonomy_get_tree($service_line_vid);
  
  $geography_name = taxonomy_vocabulary_machine_name_load('geography');
  $geography_vid = $geography_name->vid;
  $geography = taxonomy_get_tree($geography_vid);
  $n1 = array();
  $n2 = array(); 
 
  foreach ($service_line as $sv) {
   $n1[] = $tids = array($sv->tid);
  }
  
  foreach ($geography as $geo) {
   $n2[] = $tids = array($geo->tid);
  }
   
  $output .= '<table><tr class="th-row"><th>Row Labels</th>';
  foreach ($geography as $geo) {
   $output .= '<th>'.$geo->name.'</th>';
  }
  $output .= '<th>Grand Total</th>';
  $output .= '</tr>';
  $ac = '';
  for ($i =0; $i<count($service_line); $i++ ) {
	  $output .= '<tr><td>'.$service_line[$i]->name.'</td>';
	  $nids1 = taxonomy_select_nodes($n1[$i]);
	
	  for ($j =0; $j<count($geography); $j++ ) {
		  $nids2 = taxonomy_select_nodes($n2[$j]);
		  $a = check_common_nids($nids1,$nids2);
		  $ac += count($a);
		  $output .= '<td>'.count($a).'</td>';
	 }
	 $output .='<td>'.count($nids1).'</td>';
	 $output .= '</tr>';
  }

    $output .= '<tr><td>Grand Total</td>';
    for ($j =0; $j<count($geography); $j++ ) {
		$nids2 = taxonomy_select_nodes($n2[$j]);
	    $output .= '<td>'.count($nids2).'</td>';
	}
		
	$output .='<td>'.$ac.'</td>';
    $output .= '</tr></table>';
  return $output;
}

/*
 * Implement sectors_chart()
 * Use display Sector Chart.
 */
 
function sectors_chart() {
  $output='';
  $sectors_name = taxonomy_vocabulary_machine_name_load('sectors');
  $sectors_vid = $sectors_name->vid;
  $sectors = taxonomy_get_tree($sectors_vid);
  
  $geography_name = taxonomy_vocabulary_machine_name_load('geography');
  $geography_vid = $geography_name->vid;
  $geography = taxonomy_get_tree($geography_vid);
   
  $n1 = array();
  $n2 = array(); 
   
  foreach($sectors as $sec){
   $n1[] = $tids = array($sec->tid);
  }
  
  foreach ($geography as $geo) {
   $n2[] = $tids = array($geo->tid);
  }
  
  $output .= '<table><tr class="th-row"><th>Row Labels</th>';
  foreach ($geography as $geo) {
   $output .= '<th>'.$geo->name.'</th>';
  }
  $output .= '<th>Grand Total</th>';
  $output .= '</tr>';
  $ac = '';
  for ($i =0; $i<count($sectors); $i++ ) {
	  $output .= '<tr><td>'.$sectors[$i]->name.'</td>';
	  $nids1 = taxonomy_select_nodes($n1[$i]);
	 
	  for ($j =0; $j<count($geography); $j++ ) {
		  $nids2 = taxonomy_select_nodes($n2[$j]);
		  $a = check_common_nids($nids1,$nids2);
		  $ac += count($a);
		  $output .= '<td>'.count($a);
		  $output .= '</td>'; 
	 }
	 $output .='<td>'.count($nids1).'</td>';
	 $output .= '</tr>';
  }
   $output .= '<tr><td>Grand Total</td>';
    for ($j =0; $j<count($geography); $j++ ) {
		$nids2 = taxonomy_select_nodes($n2[$j]);
	    $output .= '<td>'.count($nids2).'</td>';
	}
		
	$output .='<td>'.$ac.'</td>';
    $output .= '</tr></table>';
  
  return $output;
}

/*
 * Implement all_chart()
 * Use display All Status Chart.
 */
 
function all_chart() {
  $output='';
  $status_name = taxonomy_vocabulary_machine_name_load('status');
  $status_vid = $status_name->vid;
  $status = taxonomy_get_tree($status_vid);
 
  $geography_name = taxonomy_vocabulary_machine_name_load('geography');
  $geography_vid = $geography_name->vid;
  $geography = taxonomy_get_tree($geography_vid);
  
  $n1 = array();
  $n2 = array(); 
 
  foreach ($status as $sta) {
   $n1[] = $tids = array($sta->tid);
  }
  
  foreach ($geography as $geo) {
   $n2[] = $tids = array($geo->tid);
  }
   
  $output .= '<table><tr class="th-row"><th>Row Labels</th>';
  foreach ($geography as $geo) {
   $output .= '<th>'.$geo->name.'</th>';
  }
  $output .= '<th>Grand Total</th>';
  $output .= '</tr>';
  $ac = '';
  for ($i =0; $i<count($status); $i++ ) {
	  $output .= '<tr><td>'.$status[$i]->name.'</td>';
	  $nids1 = taxonomy_select_nodes($n1[$i]);
	 
	  for ($j =0; $j<count($geography); $j++ ) {
		  $nids2 = taxonomy_select_nodes($n2[$j]);
		  $a = check_common_nids($nids1,$nids2);
		  $ac += count($a);
		  $output .= '<td>'.count($a);
		  $output .= '</td>'; 
	 }
	 $output .='<td>'.count($nids1).'</td>';
	 $output .= '</tr>';
  }
  $output .= '<tr><td>Grand Total</td>';
    for ($j =0; $j<count($geography); $j++ ) {
		$nids2 = taxonomy_select_nodes($n2[$j]);
	    $output .= '<td>'.count($nids2).'</td>';
	}
		
	$output .='<td>'.$ac.'</td>';
    $output .= '</tr></table>';
  
  return $output;
}

/*
 * Implement check_common_nids()
 * Use check the common values in arrays.
 */
 
function check_common_nids($nid1, $nid2) {
	return $commonElements = array_intersect($nid1,$nid2);
}

/*
 * Implement hook_block_info
 * Use Register a block.
 */
 
function mdl_custom_block_info() {
   $blocks['current_status'] = array(
    'info' => t('Current Status'), 
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/*
 * Implement hook_block_view
 * Use Fetch the content.
 */
 
function mdl_custom_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'current_status':
      $block['subject'] = t('Current Status');
      $block['content'] = all_chart();
      break;

  }
  return $block;
}
